In [10]:
import pandas as pd


df_mb_dani = pd.read_csv('municipios_brasileiro.csv', delimiter=';')
df_mb_dani

,CITY,STATE,Pop_residente,IDHM_Rank,Renda,Educacao,CARRO,Regiao
0,Acrelândia,AC,12538,4079,"0,584","0,466",1223,Norte
1,Assis Brasil,AC,6072,4448,"0,578","0,456",290,Norte
2,Brasiléia,AC,21398,3832,"0,619","0,485",2122,Norte
3,Bujari,AC,8471,4426,"0,603","0,439",577,Norte
4,Capixaba,AC,8798,4755,"0,601","0,398",561,Norte
...,...,...,...,...,...,...,...,...
5554,Tocantinópolis,TO,22619,2415,"0,634","0,623",3500,Norte
5555,Tupirama,TO,1574,2690,"0,629","0,593",145,Norte
5556,Tupiratins,TO,2097,4484,"0,601","0,425",98,Norte
5557,Wanderlândia,TO,10981,3352,"0,619","0,561",589,Norte
5558,Xambioá,TO,11484,2648,"0,648","0,57",848,Norte

In [11]:
traducao_colunas = {
    'CITY': 'Cidade',
    'STATE': 'Estado',
    'Pop_residente': 'Populacao_Residente',
    'IDHM_Rank': 'Rank_do_IDHM',
    'Renda': 'Renda',
    'Educacao': 'Educacao',
    'CARRO': 'Carros',
    'Regiao': 'Regiao'
}


df_mb_dani.rename(columns=traducao_colunas, inplace=True)
df_mb_dani

,Cidade,Estado,Populacao_Residente,Rank_do_IDHM,Renda,Educacao,Carros,Regiao
0,Acrelândia,AC,12538,4079,"0,584","0,466",1223,Norte
1,Assis Brasil,AC,6072,4448,"0,578","0,456",290,Norte
2,Brasiléia,AC,21398,3832,"0,619","0,485",2122,Norte
3,Bujari,AC,8471,4426,"0,603","0,439",577,Norte
4,Capixaba,AC,8798,4755,"0,601","0,398",561,Norte
...,...,...,...,...,...,...,...,...
5554,Tocantinópolis,TO,22619,2415,"0,634","0,623",3500,Norte
5555,Tupirama,TO,1574,2690,"0,629","0,593",145,Norte
5556,Tupiratins,TO,2097,4484,"0,601","0,425",98,Norte
5557,Wanderlândia,TO,10981,3352,"0,619","0,561",589,Norte
5558,Xambioá,TO,11484,2648,"0,648","0,57",848,Norte

In [12]:
# Remoção de caracteres não númericos da coluna Educação e Renda
df_mb_dani['Educacao'] = df_mb_dani['Educacao'].str.replace(r'[^\d.]+', '', regex=True)
df_mb_dani['Renda'] = df_mb_dani['Renda'].str.replace(r'[^\d.]+', '', regex=True)


# Converte a coluna Educação e Renda para tipo float
df_mb_dani['Educacao'] = pd.to_numeric(df_mb_dani['Educacao'], errors='coerce')
df_mb_dani['Renda'] = pd.to_numeric(df_mb_dani['Renda'], errors='coerce')

In [13]:
df_mb_dani.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5559 entries, 0 to 5558
Data columns (total 8 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Cidade               5559 non-null   object
 1   Estado               5559 non-null   object
 2   Populacao_Residente  5559 non-null   int64
 3   Rank_do_IDHM         5559 non-null   int64
 4   Renda                5559 non-null   int64
 5   Educacao             5559 non-null   int64
 6   Carros               5559 non-null   int64
 7   Regiao               5559 non-null   object
dtypes: int64(5), object(3)
memory usage: 347.6+ KB

In [14]:
df_novo = df_mb_dani
df_novo

,Cidade,Estado,Populacao_Residente,Rank_do_IDHM,Renda,Educacao,Carros,Regiao
0,Acrelândia,AC,12538,4079,584,466,1223,Norte
1,Assis Brasil,AC,6072,4448,578,456,290,Norte
2,Brasiléia,AC,21398,3832,619,485,2122,Norte
3,Bujari,AC,8471,4426,603,439,577,Norte
4,Capixaba,AC,8798,4755,601,398,561,Norte
...,...,...,...,...,...,...,...,...
5554,Tocantinópolis,TO,22619,2415,634,623,3500,Norte
5555,Tupirama,TO,1574,2690,629,593,145,Norte
5556,Tupiratins,TO,2097,4484,601,425,98,Norte
5557,Wanderlândia,TO,10981,3352,619,561,589,Norte
5558,Xambioá,TO,11484,2648,648,57,848,Norte

In [15]:
novo_dado = 'municipios_br2.csv'
df_novo.to_csv(novo_dado, index=False)